st1 [1985][IMP] stock_quant_manual_assign
qrtl/rpl-oca pull request #33
Opened 2021-09-22 09:39 UTC by kakurai8

[1985](https://www.quartile.co/web#view_type=form&model=project.task&id=1985&active_id=1985&menu_id=)
- for update translation, clone from OCA

2021-09-22 09:59 UTC, kakurai8 commented
（取得元）
https://github.com/OCA/stock-logistics-warehouse/commits/12.0/stock_quant_manual_assign

- A. OCAを正とする
- B. 既存を正として/i18n/ja.poファイルのみ更新する
A,Bのどちらがいいのか判断ついていないです
特に下記4. stock_quant_manual_assign/wizard/assign_manual_quants.pyの更新が不明

確認必要なファイル
1. stock_quant_manual_assign/__manifest__.py
2. stock_quant_manual_assign/i18n/ja.po
3. stock_quant_manual_assign/i18n/stock_quant_manual_assign.pot
4. stock_quant_manual_assign/wizard/assign_manual_quants.py

確認不要(と判断している)ファイル
5. 上記以外の/i18n/以下のファイル

2021-09-27 05:30 UTC, yostashiro requested changes
When our module is diverted from what's in the OCA repo, we should maintain the translation separately in our repo and OCA repo. Although it's a bit of duplicated work, I can't think of a better way to handle this at this point.

2021-09-27 05:30 UTC, yostashiro commented on stock_quant_manual_assign/wizard/assign_manual_quants.py
> +        ])
This is a regression from just overriding the module with the latest one from the OCA repo.

ref. https://github.com/OCA/stock-logistics-warehouse/pull/1064

2021-12-08 08:07 UTC, kakurai8 commented
This PR is closing.
I will recreate to adjust the translation only.

2021-12-08 08:07 UTC, closed without merging